### ISSUE TITLE
After updating to v.0.5.0 from settings menu nothing happens.  Probably a  cache issue. Need to press ctrl+f5.  Same issue on mobile.

### ISSUE THREAD

**Issue by mikkelmogensen** [nilp0inter/MiSTer_WebMenu#20] opened 2020-06-08 18:49 UTC
**Describe the bug**
See title

**Describe your setup**
- WebMenu Version: v0.5.0
- MiSTer Version: any

**To Reproduce**
1. Go to settings
2. Click on update'
3. Then  nothing

**Expected behavior**
A reload and the new content showing

**Web Browser:**
 - OS: Windows
 - Browser chrome

**Additional context**
Same issue on chrome mobile  - need to clear cache to get  new version

**Comment by nilp0inter** [comment] 2020-06-08 20:00
Duplicate of #8. Will be fixed in v0.6.0.

Thank you for reportingit !

**Closed by nilp0inter** 2020-06-08 20:00 UTC
Labels: bug, duplicate, not confirmed
